export const DAILY_PLANS_REPOSITORY = 'DAILY_PLANS_REPOSITORY';
export const DOMAN_SESSIONS_REPOSITORY = 'DOMAN_SESSIONS_REPOSITORY';
export const DOMAN_SESSION_CARDS_REPOSITORY = 'DOMAN_SESSION_CARDS_REPOSITORY';
export const DOMAN_EXPOSURE_LOGS_REPOSITORY = 'DOMAN_EXPOSURE_LOGS_REPOSITORY';
export const STUDY_PLANS_REPOSITORY = 'STUDY_PLANS_REPOSITORY';
export const PLAN_ASSIGNMENTS_REPOSITORY = 'PLAN_ASSIGNMENTS_REPOSITORY';
